### ISSUE TITLE
[ERROR] NoSuchElementException: Message: None

### ISSUE THREAD

**Issue by Tschak77** [Second-Hand-Friends/kleinanzeigen-bot#10] opened 2022-01-13 12:23 UTC
3 times of 4 runnings I will get this error

`[ERROR] NoSuchElementException: Message: None`

And the browser is showing an advertising picture after login.

**Comment by jniggemann** [comment] 2022-01-16 17:50
Using the windows binary, got this error a couple of times but can't reproduce.

**Comment by martinsznapka** [comment] 2022-02-06 21:00
> add pause at line 293
> 
> `pause(1500, 3000)` `self.web_open(f"{self.root_url}/m-meine-anzeigen.html")`
> 
> now it is running much better

Still doesn't work and same error message is displayed.

**Comment by ShadowPlug** [comment] 2022-02-09 11:58
The problem is fixed while having Adblock activated in the browser. I install the extension while the program is paused during captcha, but everytime you restart the browser/bot you need to install the chrome adblock extension again. Maybe the problem is completly gone if you Block Ads per PIHole on the whole WiFi.

**Comment by Airwave1981** [comment] 2022-02-14 12:10
> The problem is fixed while having Adblock activated in the browser. I install the extension while the program is paused during captcha, but everytime you restart the browser/bot you need to install the chrome adblock extension again. Maybe the problem is completly gone if you Block Ads per PIHole on the whole WiFi.

Thanks for that help.

I downloaded the adblock extension 
"uBlock Origin" https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm with the extension 
"Get CRX" https://chrome.google.com/webstore/search/get%20crx
as crx fle and put this into a local folder.

Then I added following line in selenium_mixin.py in line 66

```
            if self.browser_binary_location:
                browser_options.binary_location = self.browser_binary_location
                LOG.info(" -> Chrome binary location: %s", self.browser_binary_location)
```
            
**`            browser_options.add_extension(r'E:\kleinanzeigen-bot\chrome-extensions\uBlock Origin 1.41.2.0.crx')`**

`            return browser_options`


This is loading the adnblock extension automatically.

**Comment by sebthom** [comment] 2022-02-17 13:21
I made private window mode, user profile path and loading of additional extensions configurable via the config.yaml. You can play around with these settings and check what works for you. Please report back if you found a good setting.

**Comment by sebthom** [comment] 2022-02-17 16:08
@Airwave1981 @ShadowPlug @Tschak77 @martinsznapka @jniggemann @derlucas 
I now committed a change that hopefully solves this issue also in private mode and without requiring any additional config or browser plugins. please give it a try if it works for you

**Comment by jniggemann** [comment] 2022-02-17 19:33
I have tested the latest release and the message did not appear. So either pure luck, or, more likely, good job Seb! Thank you!

**Comment by martinsznapka** [comment] 2022-02-19 16:21
Works again, thank you!

**Comment by sebthom** [comment] 2022-02-19 18:32
Fixed with https://github.com/Second-Hand-Friends/kleinanzeigen-bot/commit/e4226288d3f8b51df4bff652227e5a4e10a90d87

**Closed by sebthom** 2022-02-19 18:32 UTC
Labels: bug
