### ISSUE TITLE
[Bug] Cannot publish currently - big change(s) on and before 16.5.2023 @ Kleinanzeigen?

### ISSUE THREAD

**Issue by svensvond** [Second-Hand-Friends/kleinanzeigen-bot#180] opened 2023-05-11 06:35 UTC
Cannot publish any add since about 2 weeks.

![image](https://github.com/Second-Hand-Friends/kleinanzeigen-bot/assets/37634123/1b40bd92-8c67-44c5-8ab7-7f085972b497)

**Comment by dojo90** [comment] 2023-05-12 07:59
duplicate of https://github.com/Second-Hand-Friends/kleinanzeigen-bot/issues/176

**Closed** 2023-05-15 20:02 UTC
Labels: duplicate
