### ISSUE TITLE
0.1.dev1+ged09098: Element not found or not clickable

### ISSUE THREAD

**Issue by jniggemann** [Second-Hand-Friends/kleinanzeigen-bot#109] opened 2022-09-27 15:47 UTC
Reproducible messasge `NoSuchElementException: Message: Element xpath='//select[@id='priceType']' not found or not clickable` regardless of the ads I try to post.

**Comment by tegger2000** [comment] 2022-09-27 19:10
i got the same error
it seems the ID changed to "post-ad-frontend-price", could this be ?

**Comment by sebthom** [comment] 2022-09-28 14:19
Duplicate of #106

**Closed by sebthom** 2022-09-28 14:19 UTC
