### ISSUE TITLE
Chrome failed to start: exited abnormally

### ISSUE THREAD

**Issue by lamyergeier** [Second-Hand-Friends/kleinanzeigen-bot#181] opened 2023-05-15 13:54 UTC
Operating System - Fedora38

```bash
$ google-chrome --version
Google Chrome 113.0.5672.92 

$ chromium-browser --version
Chromium 113.0.5672.63 Fedora Project

$ chromedriver --version
ChromeDriver 113.0.5672.63 (0e1a4471d5ae5bf128b1bd8f4d627c8cbd55f70c-refs/branch-heads/5672@{#912})
```

# Browser Configuration in config.yaml

```yaml
# browser configuration
browser:
  # https://peter.sh/experiments/chromium-command-line-switches/
  arguments:
    #[IP got blocked! · Issue #152 · Second-Hand-Friends/kleinanzeigen-bot](https://github.com/Second-Hand-Friends/kleinanzeigen-bot/issues/152)
    #- --user-agent=Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:108.0) Gecko/20100101 Firefox/108.0
    # https://stackoverflow.com/a/50725918/5116073
    - --disable-dev-shm-usage
    - --no-sandbox
    #- --headless
    # --start-maximized
  binary_location: #"/snap/bin/chromium.chromedriver" #"/usr/bin/chromedriver" #
  # path to custom browser executable, if not specified will be looked up on PATH
  extensions: [] # a list of .crx extension files to be loaded
  use_private_window: true
  user_data_dir: "" # see https://github.com/chromium/chromium/blob/main/docs/user_data_dir.md
  profile_name: ""
```

---

```bash
 _    _      _                           _                       _           _
| | _| | ___(_)_ __   __ _ _ __  _______(_) __ _  ___ _ __      | |__   ___ | |_
| |/ / |/ _ \ | '_ \ / _` | '_ \|_  / _ \ |/ _` |/ _ \ '_ \ ____| '_ \ / _ \| __|
|   <| |  __/ | | | | (_| | | | |/ /  __/ | (_| |  __/ | | |____| |_) | (_) | |_
|_|\_\_|\___|_|_| |_|\__,_|_| |_/___\___|_|\__, |\___|_| |_|    |_.__/ \___/ \__|
                                           |___/
                         https://github.com/Second-Hand-Friends/kleinanzeigen-bot

[INFO] Logging to [/mnt/Documents/Mobile/Data/Task/Todo/Sales/kleinanzeigen-bot.log]...
[INFO] App version: 0.1.dev1+gb82b1f7
[INFO] Loading config from [/home/lamy/opt/Kleinanzeigen/config.yaml]...
[INFO]  -> found 138 categories
[INFO] Searching for ad config files...
[INFO]  -> found 2 ad config files
[INFO] Loading ad from [/home/lamy/Documents/Mobile/Data/Task/Todo/Sales/Bike/ad_Bike.yaml]...
[INFO] Loading ad from [/home/lamy/Documents/Mobile/Data/Task/Todo/Sales/Macbook/ad_Laptop.yaml]...
[INFO] Loaded 2 ads
[INFO] Creating WebDriver session...
[INFO] Using pre-installed Chrome Driver [/usr/bin/chromedriver]
[INFO]  -> Custom chrome argument: --disable-dev-shm-usage
[INFO]  -> Custom chrome argument: --no-sandbox
[ERROR] WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/lib64/chromium-browser/chromium-browser is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x55ed2cfbbee3 <unknown>
#1 0x55ed2cc21f08 <unknown>
#2 0x55ed2cc4aa63 <unknown>
#3 0x55ed2cc46e8e <unknown>
#4 0x55ed2cc8364b <unknown>
#5 0x55ed2cc7a963 <unknown>
#6 0x55ed2cc51429 <unknown>
#7 0x55ed2cc52952 <unknown>
#8 0x55ed2cf8e459 <unknown>
#9 0x55ed2cf90b2e <unknown>
#10 0x55ed2cf90579 <unknown>
#11 0x55ed2cf91245 <unknown>
#12 0x55ed2cf96c93 <unknown>
#13 0x55ed2cf915c5 <unknown>
#14 0x55ed2cf6fd6a <unknown>
#15 0x55ed2cfa9948 <unknown>
#16 0x55ed2cfa9adb <unknown>
#17 0x55ed2cfb66ff <unknown>
#18 0x7fbf56bcd907 start_thread
#19 0x7fbf56c53870 __clone3

[113660] Failed to execute script '__main__' due to unhandled exception!
```

**Comment by sebthom** [comment] 2023-05-15 20:04
Looks like duplicate of your other issue #146

**Comment by lamyergeier** [comment] 2023-05-15 21:22
@sebthom Unfortunately not as in [#146](https://github.com/Second-Hand-Friends/kleinanzeigen-bot/issues/146), chrome actually starts and remains blank the whole duration as shown in the attached image in that issue. 

In this case the chrome doesn't even start. Also, the current issue is from Fedora 38, while [#146](https://github.com/Second-Hand-Friends/kleinanzeigen-bot/issues/146) is from Ubuntu 22.04

**Closed** 2023-09-27 16:46 UTC
Labels: wontfix
