### ISSUE TITLE
end user test on Linux

### ISSUE THREAD

**Issue by sebthom** [Second-Hand-Friends/kleinanzeigen-bot#7] opened 2022-01-12 21:25 UTC
The app should be tested on Linux (incl. publishing some ads) to verify it's functionality.

**Comment by derlucas** [comment] 2022-01-30 20:25
I can help out. Already installed it and tried to create an Ad.

Getting the following Error:
```

$ ./kleinanzeigen-bot publish
[INFO] Logging to [/home/lucas/temp/ebaykleinanzeigen/kleinanzeigen-bot.log]...
[INFO] App version: 0.1.dev1+gea04b85
[INFO] Loading config from [/home/lucas/temp/ebaykleinanzeigen/config.yaml]...
[INFO]  -> found 10 categories
[INFO] Searching for ad files...
[INFO]  -> found 1 ad file
[INFO] Loading ad file from [/home/lucas/temp/ebaykleinanzeigen/ads/zino.yaml]...
[INFO]  -> loaded 1 ad
[INFO] Creating WebDriver session...
[INFO]  -> Custom chrome argument: --disable-dev-shm-usage
[INFO]  -> Custom chrome argument: --no-sandbox
[INFO] New WebDriver session is: 6XXXfb33ee1e http://localhost:51425
[INFO] Logging in as [lucas@XXX.de]...
[WARNING] ############################################
[WARNING] # Captcha present! Please solve and close the captcha, but DON'T click 'Einloggen'.
[WARNING] ############################################
[INFO]  ... pausing for 1590 ms ...
[INFO] Processing 1/1: 'XXXX' from [/home/lucas/temp/ebaykleinanzeigen/ads/zino.yaml]...
[INFO] Deleting ad 'XXXX' if already present...
[ERROR] NoSuchElementException: Message: None
```

my config is:
```

$ cat config.yaml
ad_files:
  - "ads/zino.yaml"

ad_defaults:
  active: true
  type: OFFER
  price_type: NEGOTIABLE
  shipping_type: SHIPPING
  contact:
    name: Lucas
  republication_interval: 7

login:
  username: XXXX
  password: XXXX
```

in the ads/zino.yaml:

```
$ cat ads/zino.yaml
active: true
title: XXX
description: >
  Biete hier mein XXX an.

  Abholung nicht moeglich, nur Versand. Keine Rueckname.

  (foo bar text)

category: 185/249
price: 250

```

running with "-v" switch get the following stack trace:
```

[ERROR] Traceback (most recent call last):
  File "kleinanzeigen_bot/selenium_mixin.py", line 163, in web_await
  File "selenium/webdriver/support/wait.py", line 89, in until
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
#0 0x555b7969ea44 <unknown>
#1 0x555b7907c6dd <unknown>
#2 0x555b790bb351 <unknown>
#3 0x555b790bb471 <unknown>
#4 0x555b790f9a75 <unknown>
#5 0x555b790e256d <unknown>
#6 0x555b790f6dcf <unknown>
#7 0x555b790e2403 <unknown>
#8 0x555b790ab3f2 <unknown>
#9 0x555b790ace6c <unknown>
#10 0x555b796cedbf <unknown>
#11 0x555b796e872d <unknown>
#12 0x555b796d0e75 <unknown>
#13 0x555b796e9206 <unknown>
#14 0x555b796c5ca1 <unknown>
#15 0x555b79705137 <unknown>
#16 0x555b79705316 <unknown>
#17 0x555b79720ad5 <unknown>
#18 0x7f6ae5d63259 <unknown>


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "kleinanzeigen_bot/__main__.py", line 8, in <module>
  File "kleinanzeigen_bot/__init__.py", line 470, in main
  File "kleinanzeigen_bot/__init__.py", line 78, in run
  File "kleinanzeigen_bot/__init__.py", line 323, in publish_ads
  File "kleinanzeigen_bot/__init__.py", line 331, in publish_ad
  File "kleinanzeigen_bot/__init__.py", line 297, in delete_ad
  File "kleinanzeigen_bot/selenium_mixin.py", line 188, in web_find
  File "kleinanzeigen_bot/selenium_mixin.py", line 165, in web_await
selenium.common.exceptions.NoSuchElementException: Message: None
```


Am i missing config options? How should i debug it further?

**Comment by sebthom** [comment] 2022-01-30 20:56
I cannot test myself atm. I would have expected this to work. Maybe the HTML layout has changed and we need to adjust. You are very welcome to investigate further.

**Comment by sebthom** [comment] 2022-02-21 17:08
@jniggemann do you think you can work on this issues, i.e. confirm the app works as expected on Linux

**Comment by jniggemann** [comment] 2022-02-22 13:57
Using 0.1.de1+g881eb0d on Debian bullseye (11.2 with latest updates) , app works as expected. I can verify as well as delete+publish a new ad.

@derlucas: I can't reproduce the issue and close this, please reopen if the error persists in the latest version.

**Closed by jniggemann** 2022-02-22 13:57 UTC
Labels: help wanted
