### ISSUE TITLE
NoSuchElementException: Message: Element xpath='//select[@id='priceType']' not found or not clickable

### ISSUE THREAD

**Issue by Keff789** [Second-Hand-Friends/kleinanzeigen-bot#110] opened 2022-09-28 12:36 UTC
Current version freshly synced, installed from source. Getting the following error "NoSuchElementException: Message: Element xpath='//select[@id='priceType']' not found or not clickable".
[kleinanzeigen_bot.log](https://github.com/Second-Hand-Friends/kleinanzeigen-bot/files/9664920/kleinanzeigen_bot.log)

**Comment by sebthom** [comment] 2022-09-28 14:19
Duplicate of #106

**Closed by sebthom** 2022-09-28 14:19 UTC

**Comment by ChristopherLenz** [comment] 2022-10-22 10:20
@sebthom 

Using the Docker image with the recommended "X11 - X Window System" still gives the same error. Tried the official image and a homemade one

```
[INFO]  ... pausing for 2000 ms ...
[INFO]  ... pausing for 2000 ms ...
[ERROR] NoSuchElementException: Message: Element xpath='//select[@id='priceType']' not found or not clickable

[8] Failed to execute script '__main__' due to unhandled exception!
10:16:07 Error - exited with status 0 at line 24:
   21
   22   cd /mnt/data
   23
   24   /opt/kleinanzeigen-bot --config $CONFIG_FILE "$@"
```

**Comment by sebthom** [comment] 2022-10-22 14:57
@ChristopherLenz what is the full stacktrace? try to run it with `--verbose`

**Comment by ChristopherLenz** [comment] 2022-10-23 11:41
@sebthom 

```
[DEBUG]  -> Opening [https://www.ebay-kleinanzeigen.de/p-kategorie-aendern.html#?path=161/225/speicher]...
[INFO]  ... pausing for 2000 ms ...
[INFO]  ... pausing for 1566 ms ...
[ERROR] Traceback (most recent call last):
  File "kleinanzeigen_bot/selenium_mixin.py", line 246, in web_await
    return WebDriverWait(self.webdriver, timeout).until(condition)  # type: ignore[no-any-return]
  File "selenium/webdriver/support/wait.py", line 90, in until
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
#0 0x55ea3d270d53 <unknown>
#1 0x55ea3d05d786 <unknown>
#2 0x55ea3d096048 <unknown>
#3 0x55ea3d096141 <unknown>
#4 0x55ea3d0d37f4 <unknown>
#5 0x55ea3d0bb9cd <unknown>
#6 0x55ea3d0d182f <unknown>
#7 0x55ea3d0bb863 <unknown>
#8 0x55ea3d08a316 <unknown>
#9 0x55ea3d08b8e8 <unknown>
#10 0x55ea3d2aefad <unknown>
#11 0x55ea3d2b0bf0 <unknown>
#12 0x55ea3d2b06f7 <unknown>
#13 0x55ea3d2b1285 <unknown>
#14 0x55ea3d29e21b <unknown>
#15 0x55ea3d2b15b6 <unknown>
#16 0x55ea3d29266f <unknown>
#17 0x55ea3d2c9fe5 <unknown>
#18 0x55ea3d2ca183 <unknown>
#19 0x55ea3d2e37e0 <unknown>
#20 0x7f60c3f98ea7 <unknown>


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "kleinanzeigen_bot/__init__.py", line 468, in publish_ad
    self.web_select(By.XPATH, "//select[@id='price-type-react']", price_type)
  File "kleinanzeigen_bot/selenium_mixin.py", line 360, in web_select
    elem = self.web_await(
  File "kleinanzeigen_bot/selenium_mixin.py", line 249, in web_await
    raise exception_on_timeout() from ex
selenium.common.exceptions.NoSuchElementException: Message: Element xpath='//select[@id='price-type-react']' not found or not clickable


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "kleinanzeigen_bot/selenium_mixin.py", line 246, in web_await
    return WebDriverWait(self.webdriver, timeout).until(condition)  # type: ignore[no-any-return]
  File "selenium/webdriver/support/wait.py", line 90, in until
selenium.common.exceptions.TimeoutException: Message:


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "kleinanzeigen_bot/__main__.py", line 8, in <module>
    kleinanzeigen_bot.main(sys.argv)
  File "kleinanzeigen_bot/__init__.py", line 660, in main
    KleinanzeigenBot().run(args)
  File "kleinanzeigen_bot/__init__.py", line 78, in run
    self.publish_ads(ads)
  File "kleinanzeigen_bot/__init__.py", line 410, in publish_ads
    self.publish_ad(ad_file, ad_cfg, ad_cfg_orig)
  File "kleinanzeigen_bot/__init__.py", line 474, in publish_ad
    self.web_select(By.XPATH, "//select[@id='priceType']", price_type)
  File "kleinanzeigen_bot/selenium_mixin.py", line 360, in web_select
    elem = self.web_await(
  File "kleinanzeigen_bot/selenium_mixin.py", line 249, in web_await
    raise exception_on_timeout() from ex
selenium.common.exceptions.NoSuchElementException: Message: Element xpath='//select[@id='priceType']' not found or not clickable


[8] Failed to execute script '__main__' due to unhandled exception!
11:39:19 Error - exited with status 0 at line 24:
   21
   22   cd /mnt/data
   23
   24   /opt/kleinanzeigen-bot --config $CONFIG_FILE "$@"
make: *** [Makefile:27: publish] Error 1
```
