### ISSUE TITLE
[BUG] Error message with more than 25 adverts/display on 2+ pages

### ISSUE THREAD

**Issue by PlanetDyna** [Second-Hand-Friends/kleinanzeigen-bot#278] opened 2024-03-17 14:28 UTC
### ✔️ Expected Behaviour

All adverts are downloaded. Not just the one on page 1.

### 🐞 Actual Behaviour

Error message/stop the download if the adverts are on page 2 for example.

### 📋 Steps to Reproduce

Create more than 25 adverts.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by euberdeveloper** [comment] 2024-03-22 16:27
Isn't it a duplicate of: #263

**Comment by TylonHH** [comment] 2024-03-23 13:01
As I have also more then 25 ads I searched here and fpund all this related issues:
https://github.com/Second-Hand-Friends/kleinanzeigen-bot/issues/170
https://github.com/Second-Hand-Friends/kleinanzeigen-bot/issues/149

This is the error message I got. I hope this helps someone to debug:
```[INFO] It seems like you have many ads!```
```[ERROR] TimeoutError: No HTML elements found using CSS selector 'button.jsx-2828608826' within 5 seconds.```

I use the latetest exed for windows.

**Comment by provinzio** [comment] 2024-05-30 17:02
Does the PR fix the issue? @PlanetDyna

**Comment by sebthom** [comment] 2024-06-01 09:12
Closing issue as it is supposed to be fixed by #298. Feel free to re-open if issue still persists

**Closed by sebthom** 2024-06-01 09:12 UTC
Labels: bug
